2706 2й спринт промежуточная работа с контекстом
Nadezhda-Yarovaya/react-burger pull request #3
Opened 2022-06-27 17:23 UTC by Nadezhda-Yarovaya

добавлены в контекст - все ингредиенты, только начинки и номер заказа (с сервера) 
также в отдельный контекст добавлена общая сумма (2 раза считаем булку по полной стоимости, как написано в тренажере и сказано на вебинаре)

2022-06-27 19:12 UTC, kyzinatra commented on src/components/app/app.jsx
>    const [width, height] = useWindowSize();
Можно лучше: вместо `[{ name: 'тест' }]` лучше поставить `null` обозначая, что ингредиентов нет и проверят это состояние в уловном ренере ниже (рендерить компонент, только если есть что рендерить)

2022-06-27 19:14 UTC, kyzinatra commented on src/components/app/app.jsx
> +        </IngredientsContext.Provider>
Надо исправить: В условном рендере лучше рендерить компоненты <ModalIngredient> к примеру (название с большой буквы)

2022-06-27 19:38 UTC, kyzinatra requested changes
Выглядит очень круто! Видно, что проделана большая работа.

Что важно исправить:

- Не писать 2 раза в коде 1 и тот же компонент `TotalSum` это сильно загружает код
- по чек-листу папка должна называться services, а не context
- Булка в запрос должна передаваться с 2 сторон

Можно лучше:

- Файл data.js  более не используется так что можно его удалить.
- `mobile-constructor-element.js` лучше переименовать в `.jsx`
- В условном рендере рендерить компоненты
- Отдельные логические части стоит выносить в отдельные компоненты. app.jsx в идеале должен рендерить всего несколько основных компонентов, которые уже в свою очередь рендерят остальное
- Не использовать лесенку тренарных операторов. Обычно про такие ступеньки шутят, что это индусский код :). Такой код иногда сложно понять даже написавшему

Что понравилось:

- Отличная обработка запросов
- Очень круто, что вы решили сделать и мобильную версию, хоть над ней и нужно еще поработать
- Мне понравилось как вы используете хуки и то, ка написали свой.

2022-06-27 19:38 UTC, kyzinatra commented on src/components/app/app.jsx
> +                    ? isMobileOrdered
Можно лучше: саму секцию тоже лучше вынести в отдельный компонент, это разгрузит компонент от лишних состояний и кода

2022-06-27 19:38 UTC, kyzinatra commented on src/components/app/app.jsx
> +                  <></>
Можно лучше: лучше не использовать цикл тренарных операторов `a ? b ? d : k : c` такой код плохо читается и в нем сложно разобраться

2022-06-27 19:38 UTC, kyzinatra commented on src/components/app/app.jsx
> +                ) : (
Надо исправить: не стоит прописывать 2 раза по сути один и тот же компонент `TotalSum` для разных устройств. Имеет смысл обьеденить его в 1 а дальше управлять им с помощью средств `css`

2022-06-27 19:38 UTC, kyzinatra commented on src/components/app/app.jsx
> +} from '../../contexts/appContexts';
Надо исправить: по чек-листу папка должна называться `services`, а не `context`

2022-06-27 19:38 UTC, kyzinatra commented on src/components/app/app.jsx
> +      throw new Error(`Такого типа экшна нет: ${action.type}`);
Можно лучше: обычно в `default` принято возвращать состояние без изменений, а не выбрасывать ошибку. Это нужно для того, чтобы если мы захотил получить какое-то исходное состояние редьюсера мы смогли отправить пробный экшен `@@INIT`

2022-06-27 19:38 UTC, kyzinatra commented on src/components/burger-ingredients/burger-ingredients.jsx
Можно лучше: для краткости можно использовать деструкторизацию:
```js
const {mainIngredients} = useContext(IngredientsContext);
```

2022-06-27 19:38 UTC, kyzinatra commented on src/components/app/app.jsx
>    const [isPerformed, setIsPerformed] = useState(false);
Можно лучше: лучше не разделять функционал для мобильных версий и десктоп. Особенно в рамках 1 компонента. Обычно предпочитают изменять только внешний вид, используя преимущественно css, но если это крайне необходимо, то стоит разделить версии в разные компоненты, чтобы не мешать все в кучу. Но в данном случае я думаю, что для мобильных версий будет достаточно меда-запросов в css

Подробнее: http://htmlbook.ru/css/media

2022-06-27 19:38 UTC, kyzinatra commented on src/components/app/app.jsx
> +        setIsPerformed(!isPerformed);
Надо исправить: булка в запрос должна передаваться с 2 сторон
```js
ingredientsFormed // ["C7", "C5", "C4", "C7"]
```

2022-06-28 13:36 UTC, kyzinatra commented on src/components/app/app.jsx
> +        setIsPerformed(!isPerformed);
Хорошо, во время 2 итерации уделю время мобильной верии, но все что я скажу будет рекомендацией потому что этого не требудет спринт)

2022-06-28 13:39 UTC, Nadezhda-Yarovaya commented on src/components/app/app.jsx
> +        setIsPerformed(!isPerformed);
спасибо!!

2022-06-28 16:51 UTC, kyzinatra commented on src/services/app-contexts.jsx
> +export const IfMobileContext = React.createContext({});
Можно лучше: сейчас только заметил. У этого файла не обязательно расширение `.jsx` так как в нем нет jsx кода. Можно просто `.js`

2022-06-28 16:55 UTC, kyzinatra commented
Поздравляю! Ваша работа принята.

Вы отлично потрудились.

Удачного дальнейшего обучения.

2022-06-28 16:56 UTC, kyzinatra commented on src/components/constructor-list/constructor-list.module.css
> +}
Кнопка оформить заказ на десктопе уехала. Можно исправить если убрать свойство `min-height` вроде ничего не ломает. Думаю тут достаточно просто marginов

2022-06-28 16:58 UTC, kyzinatra commented
На мобилках у меня есть правый скрол из-за меню, которое не влазит
<img width="400" alt="image" src="https://user-images.githubusercontent.com/51288221/176238855-869c0756-e0da-4943-b437-c2a1e5266962.png">

2022-06-28 17:00 UTC, kyzinatra commented
стоит убрать скругления к заказов в мобильной версии 
<img width="371" alt="image" src="https://user-images.githubusercontent.com/51288221/176239475-5ea75c7f-eeda-4ff0-a43d-fd112d76ae1f.png">
<img width="332" alt="image" src="https://user-images.githubusercontent.com/51288221/176239581-90ec3c0f-f78b-41c9-ab79-d7a5211ca4f9.png">

2022-06-28 17:06 UTC, kyzinatra commented
Было бы круто удалять элементы по свайпу на мобильных версиях. Выглядит круто.
<img width="318" alt="image" src="https://user-images.githubusercontent.com/51288221/176239961-6ed404c2-1d57-4d10-8531-6780c0474b02.png">

Это можно сделать с помощью событий (touch events)[https://habr.com/ru/post/592317/]

Я думаю, что если поискать то точно найдутся библиотеки для этого, но я бы написал сам. Картину можно поставить либо блоком под элемент коструктора, либо прямо справа и свойство `oveflow: hidden` для элементов.

Свойп следует считать законченным если 40% пройдено, далее его завершаем. 

Подробнее с примером: http://www.javascriptkit.com/javatutors/touchevents2.shtml#:~:text=Swiping%20in%20touch%20is%20the,%2C%20well%2C%20%22swipe%22.

2022-06-28 17:09 UTC, kyzinatra commented
2 скролла лучше удалить 
![image](https://user-images.githubusercontent.com/51288221/176242086-67540ca4-37c4-410f-8ac5-316f72604c0c.png)
просто оставьте сплошую ленту без ограничения высоты. и убрать внутренний скролл

2022-06-28 17:10 UTC, kyzinatra commented
Немножко поехали булочки
![image](https://user-images.githubusercontent.com/51288221/176242423-607abc90-5ab1-43fa-a052-7a83825546f4.png)

2022-06-28 17:12 UTC, kyzinatra reviewed
Хорошая работа, здорово, что вы решили сделать мобильлную версию, для боевых проектов это необходимо). Успехов в дальнейшем обучении

2022-06-28 17:20 UTC, Nadezhda-Yarovaya commented on src/components/constructor-list/constructor-list.module.css
> +}
Большое спасибо за комментарии!
Буду допиливать )

2022-06-29 08:26 UTC, merged